---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[mokhan-myface::default]
      - recipe[mokhan-myface::capistrano]
      - recipe[mokhan-myface::delayed_job]
      - recipe[mokhan-myface::nginx]
      - recipe[mokhan-myface::unicorn]
      - recipe[mokhan-myface::nodejs]
      - recipe[mokhan-myface::rbenv]
    attributes:
